grails-app/domain/org/yosy/Usuario.groovy
package org.yosy

import java.util.Date;

class Usuario {

	static hasMany = [deseos:Deseo]

	String nombre
	String email
	String password
	int image
	Date fechaAlta
	TipoUsuario tipoUsuario
	EstadoUsuario estadoUsuario

	static mapping = { id generator: 'native' }

	static constraints = {
		nombre(nullable: false,unique:true)
		email(email:true,unique:true)
		password(blank:false, password:true)
	}
}

grails-app/controllers/LoginController.groovy
//import grails.converters.JSON

//import javax.servlet.http.HttpServletResponse
//
//import org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils
//
//import org.springframework.security.authentication.AccountExpiredException
//import org.springframework.security.authentication.CredentialsExpiredException
//import org.springframework.security.authentication.DisabledException
//import org.springframework.security.authentication.LockedException
//import org.springframework.security.core.context.SecurityContextHolder as SCH
//import org.springframework.security.web.WebAttributes
//import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter

class LoginController {

	/**
	 * Dependency injection for the authenticationTrustResolver.
	 */
//	def authenticationTrustResolver
//
//	/**
//	 * Dependency injection for the springSecurityService.
//	 */
//	def springSecurityService
//
//	/**
//	 * Default action; redirects to 'defaultTargetUrl' if logged in, /login/auth otherwise.
//	 */
//	def index = {
//		if (springSecurityService.isLoggedIn()) {
//			redirect uri: SpringSecurityUtils.securityConfig.successHandler.defaultTargetUrl
//		}
//		else {
//			redirect action: 'auth', params: params
//		}
//	}
//
//	/**
//	 * Show the login page.
//	 */
//	def auth = {
//
//		def config = SpringSecurityUtils.securityConfig
//
//		if (springSecurityService.isLoggedIn()) {
//			redirect uri: config.successHandler.defaultTargetUrl
//			return
//		}
//
//		String view = 'auth'
//		String postUrl = "${request.contextPath}${config.apf.filterProcessesUrl}"
//		render view: view, model: [postUrl: postUrl,
//		                           rememberMeParameter: config.rememberMe.parameter]
//	}
//
//	/**
//	 * The redirect action for Ajax requests.
//	 */
//	def authAjax = {
//		response.setHeader 'Location', SpringSecurityUtils.securityConfig.auth.ajaxLoginFormUrl
//		response.sendError HttpServletResponse.SC_UNAUTHORIZED
//	}
//
//	/**
//	 * Show denied page.
//	 */
//	def denied = {
//		if (springSecurityService.isLoggedIn() &&
//				authenticationTrustResolver.isRememberMe(SCH.context?.authentication)) {
//			// have cookie but the page is guarded with IS_AUTHENTICATED_FULLY
//			redirect action: 'full', params: params
//		}
//	}
//
//	/**
//	 * Login page for users with a remember-me cookie but accessing a IS_AUTHENTICATED_FULLY page.
//	 */
//	def full = {
//		def config = SpringSecurityUtils.securityConfig
//		render view: 'auth', params: params,
//			model: [hasCookie: authenticationTrustResolver.isRememberMe(SCH.context?.authentication),
//			        postUrl: "${request.contextPath}${config.apf.filterProcessesUrl}"]
//	}
//
//	/**
//	 * Callback after a failed login. Redirects to the auth page with a warning message.
//	 */
//	def authfail = {
//
//		def username = session[UsernamePasswordAuthenticationFilter.SPRING_SECURITY_LAST_USERNAME_KEY]
//		String msg = ''
//		def exception = session[WebAttributes.AUTHENTICATION_EXCEPTION]
//		if (exception) {
//			if (exception instanceof AccountExpiredException) {
//				msg = g.message(code: "springSecurity.errors.login.expired")
//			}
//			else if (exception instanceof CredentialsExpiredException) {
//				msg = g.message(code: "springSecurity.errors.login.passwordExpired")
//			}
//			else if (exception instanceof DisabledException) {
//				msg = g.message(code: "springSecurity.errors.login.disabled")
//			}
//			else if (exception instanceof LockedException) {
//				msg = g.message(code: "springSecurity.errors.login.locked")
//			}
//			else {
//				msg = g.message(code: "springSecurity.errors.login.fail")
//			}
//		}
//
//		if (springSecurityService.isAjax(request)) {
//			render([error: msg] as JSON)
//		}
//		else {
//			flash.message = msg
//			redirect action: 'auth', params: params
//		}
//	}
//
//	/**
//	 * The Ajax success redirect url.
//	 */
//	def ajaxSuccess = {
//		render([success: true, username: springSecurityService.authentication.name] as JSON)
//	}
//
//	/**
//	 * The Ajax denied redirect url.
//	 */
//	def ajaxDenied = {
//		render([error: 'access denied'] as JSON)
//	}
}

grails-app/views/login/_login.gsp
<%@ page import="org.yosy.Usuario"%>
<div class="centerPopUpDiv" style="margin-left: 110px;">
	<div class="nav" style="color: black;">
		<span class="menuButton linkCerrar"
			onclick="hideLogin(); document.getElementById('div_login').style.display = 'block'; document.getElementById('div_registro').style.display = 'none'; return false; "> <g:message
				code="default.close.label" />
		</span>
	</div>
	<div class="body">
		<div id="div_login" style="float: left; margin: 0 0 0 8%; width: 80%;">
			<h1 class="ttl_login">
				<g:message code="default.login.label" />
			</h1>
			<g:if test="${flash.message}">
				<div class="message"
					style="color: red; margin: 10px 0px; font-weight: bold;">
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
				<div class="errors">
					<g:renderErrors bean="${usuarioInstance}" as="list" />
				</div>
			</g:hasErrors>
			<div>
				${message}
			</div>
			<g:formRemote url="[ controller: 'user', action: 'login']"
				name="login" on401="return false;"
				onSuccess="hideLogin(); loginLink(); return false;"
				onFailure="ShowLoginMsg('Login incorrecto'); return false;">
				<table>
					<tbody>
						<tr class="prop">
							<td valign="top" class="name"><label for="email"><g:message
										code="usuario.email.label" default="Email" /></label></td>
							<td valign="top"
								class="value ${hasErrors(bean: usuarioInstance, field: 'email', 'errors')}">
								<g:textField name="email" value="${usuarioInstance?.email}" />
							</td>
						</tr>
						<tr class="prop">
							<td valign="top" class="name"><label for="password"><g:message
										code="usuario.password.label" default="Contraseña" /></label></td>
							<td valign="top"
								class="value ${hasErrors(bean: usuarioInstance, field: 'password', 'errors')}">
								<g:passwordField name="password" value="" type="password" />
							</td>
						</tr>
						<tr>
							<td colspan=2>
								<span class="linkBlue" onclick="document.getElementById('div_login').style.display = 'none'; document.getElementById('div_registro').style.display = 'block';">
									Regístrate
								</span>
								</br>
								<div class="buttons">
									<span class="button" style="display:none;"> 
										<g:submitToRemote url="[controller: 'user', action: 'login']" id="botonLogin" onFailure="ShowLoginError('ErrorLogin'); return false;" onSuccess="hideLogin(); showResponse('Login correcto'); loginLink();" value="${message(code: 'default.button.login.label', default: 'Login')}" />
									</span>
									<img style="width: 148px; height: 37px; cursor: pointer; margin: 5% 0 0 0;"  src="${resource(dir:'images',file:'boton.png')}">
									<div class="btn_login" onclick="$('#botonLogin').click()">
										Entrar
									</div>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</g:formRemote>
			<div style=" display:none; color: red; margin: 10px 0px; font-weight: bold;">
				<label id="lblErrorLogin" style="display: none;"> <g:message
						code="errors.login.errorpassemail"
						default="El email o la contraseña no son correctos." />
				</label> <label id="lblErrorPasswordVacio" style="display: none;"> <g:message
						code="errors.login.erroremptypass"
						default="El campo de contraseña no puede estar vacio." />
				</label>
			</div>
		</div>
		<div id="div_registro" style="float: left; margin: 0 0 0 8%; width: 80%; display: none;">
			<h1 class="ttl_register">
				<g:message code="default.register.label" />
			</h1>
			<g:formRemote url="[ controller: 'user', action: 'register']"
				name="register" on401="return false;"
				onSuccess=" hideLogin(); return false;">
				<div class="dialog">
					<table>
						<tbody>
							<tr class="prop">
								<td valign="top" class="name"><label for="email"><g:message
											code="usuario.email.label" default="Email" /></label></td>
								<td valign="top"
									class="value ${hasErrors(bean: usuarioInstance, field: 'email', 'errors')}">
									<g:textField class="emailRegistro" name="email" value="${usuarioInstance?.email}" />
									<img src="images/loader.gif" alt="" id="imgLoadingEmail" style="display:none;" />
								</td>
							</tr>
							<tr class="prop">
								<td valign="top" class="name"><label for="nombre"><g:message
											code="usuario.nick.label" default="Nick" /></label></td>
								<td valign="top"
									class="value ${hasErrors(bean: usuarioInstance, field: 'nick', 'errors')}">
									<g:textField name="nombre" value="${usuarioInstance?.nombre}" />
									<img src="images/loader.gif" alt="" id="imgLoadingNick" style="display:none;" />
								</td>
							</tr>
							<tr class="prop">
								<td valign="top" class="name"><label for="password"><g:message
											code="usuario.password.label" default="Contraseña" /></label></td>
								<td valign="top"
									class="value ${hasErrors(bean: usuarioInstance, field: 'password', 'errors')}">
									<g:passwordField name="passwordRegistro" value="" type="password" />
								</td>
							</tr>
							<tr class="prop">
								<td valign="top" class="name"><label for="password"><g:message
											code="usuario.passwordRepeat.label"
											default="Repite contraseña" /></label></td>
								<td valign="top" class="value"><g:passwordField
										name="passwordRepeat" value="" type="password" /></td>
							</tr>
							<tr>
								<td colspan="2">
	
									<div class="buttons">
										<span id="spanBtnRegister" class="button" style="display:none;"> 
											<g:submitToRemote id="btnRegister"
												url="[controller: 'user', action: 'register']"
												onFailure="showLogin()"
												onSuccess="hideLogin(); showResponse('Registro completado')"
												value="${message(code: 'default.button.register.label', default: 'Regístrate')}" />
										</span>
										<img style="width: 148px; height: 37px; cursor: pointer; margin: 5% 0 0 43%;" src="${resource(dir:'images',file:'boton.png')}ç">
										<div class="btn_register"  onclick="$('#btnRegister').click()" >
											Regístrate
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<div style="color: red; margin: 10px 0px; font-weight: bold;">
										<label id="lblErrorRegisterCamposVacios" style="display: none;"> <g:message
												code="errors.login.errorregister.camposvacios"
												default="Hay campos vacios." />
										</label>
										<label id="lblErrorRegisterEmail" style="display: none;"> <g:message
												code="errors.login.errorregister.email"
												default="El email no es correcto." />
										</label>
										<label id="lblErrorRegisterPass" style="display: none;"> <g:message
												code="errors.login.errorregisterpassword"
												default="Las contraseñas no coinciden." />
										</label>
										<label id="lblErrorEmailVacio" style="display: none;"> <g:message
												code="errors.login.erroremptyemail"
												default="El campo de email no puede estar vacio." />
										</label> <label id="lblErrorEmailRepetido" style="display: none;"> <g:message
												code="errors.login.erroremailrepeat"
												default="El campo de email está repetido." />
										</label> <label id="lblErrorNickRepetido" style="display: none;"> <g:message
												code="errors.login.errornickrepeat"
												default="El campo de nombre está repetido." />
										</label>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</g:formRemote>
			<g:if test="${flash.message}">
				<div class="message"
					style="color: red; margin: 10px 0px; font-weight: bold;">
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
				<div class="errors">
					<g:renderErrors bean="${usuarioInstance}" as="list" />
				</div>
			</g:hasErrors>
			<div>
				${message}
			</div>
		</div>

	</div>
</div>

grails-app/views/login/auth.gsp
<html>
<head>
	<meta name='layout' content='main'/>
	<title><g:message code="springSecurity.login.title"/></title>
	<style type='text/css' media='screen'>
	#login {
		margin: 15px 0px;
		padding: 0px;
		text-align: center;
	}

	#login .inner {
		width: 340px;
		padding-bottom: 6px;
		margin: 60px auto;
		text-align: left;
		border: 1px solid #aab;
		background-color: #f0f0fa;
		-moz-box-shadow: 2px 2px 2px #eee;
		-webkit-box-shadow: 2px 2px 2px #eee;
		-khtml-box-shadow: 2px 2px 2px #eee;
		box-shadow: 2px 2px 2px #eee;
	}

	#login .inner .fheader {
		padding: 18px 26px 14px 26px;
		background-color: #f7f7ff;
		margin: 0px 0 14px 0;
		color: #2e3741;
		font-size: 18px;
		font-weight: bold;
	}

	#login .inner .cssform p {
		clear: left;
		margin: 0;
		padding: 4px 0 3px 0;
		padding-left: 105px;
		margin-bottom: 20px;
		height: 1%;
	}

	#login .inner .cssform input[type='text'] {
		width: 120px;
	}

	#login .inner .cssform label {
		font-weight: bold;
		float: left;
		text-align: right;
		margin-left: -105px;
		width: 110px;
		padding-top: 3px;
		padding-right: 10px;
	}

	#login #remember_me_holder {
		padding-left: 120px;
	}

	#login #submit {
		margin-left: 15px;
	}

	#login #remember_me_holder label {
		float: none;
		margin-left: 0;
		text-align: left;
		width: 200px
	}

	#login .inner .login_message {
		padding: 6px 25px 20px 25px;
		color: #c33;
	}

	#login .inner .text_ {
		width: 120px;
	}

	#login .inner .chk {
		height: 12px;
	}
	</style>
</head>

<body>
<div id='login'>
	<div class='inner'>
		<div class='fheader'><g:message code="springSecurity.login.header"/></div>

		<g:if test='${flash.message}'>
			<div class='login_message'>${flash.message}</div>
		</g:if>

		<form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off'>
			<p>
				<label for='username'><g:message code="springSecurity.login.username.label"/>:</label>
				<input type='text' class='text_' name='j_username' id='username'/>
			</p>

			<p>
				<label for='password'><g:message code="springSecurity.login.password.label"/>:</label>
				<input type='password' class='text_' name='j_password' id='password'/>
			</p>

			<p id="remember_me_holder">
				<input type='checkbox' class='chk' name='${rememberMeParameter}' id='remember_me' <g:if test='${hasCookie}'>checked='checked'</g:if>/>
				<label for='remember_me'><g:message code="springSecurity.login.remember.me.label"/></label>
			</p>

			<p>
				<input type='submit' id="submit" value='${message(code: "springSecurity.login.button")}'/>
			</p>
		</form>
	</div>
</div>
<script type='text/javascript'>
	<!--
	(function() {
		document.forms['loginForm'].elements['j_username'].focus();
	})();
	// -->
</script>
</body>
</html>

grails-app/views/login/denied.gsp
<head>
<meta name='layout' content='main' />
<title><g:message code="springSecurity.denied.title" /></title>
</head>

<body>
<div class='body'>
	<div class='errors'><g:message code="springSecurity.denied.message" /></div>
</div>
</body>