grails-app/domain/org/yosy/Deseo.groovy
package org.yosy

class Deseo {

	static hasMany =	[
		comentarios:Comentario,
		votos:Voto
	]

	static belongsTo = [usuario:Usuario,categoria:Categoria,localidad:Localidad]

	String titulo
	String descripcion
	Date fechaModificacion
	Date fechaCreacion
	Estado estado
	SortedSet comentarios

	static mapping = {
		id generator: 'native'
		sort fechaCreacion:"desc"
	}

	static constraints = {
		titulo(nullable:true)
		categoria(nullable:true)
		localidad(nullable:true)
	}
}

grails-app/views/index/_grantWhis.gsp
<g:javascript library="jquery" plugin="jquery" />
<div class="texto_legal">
<div class="navigacion_nivel_dos">
	<g:link controller="index" class="navigacion_nivel_uno">
							Inicio
						</g:link>
		&nbsp; > Conceder deseos
</div>
<div class="one_half">
<h2>El origen</h2>
<p>El verano pasado tuvimos la suerte de conocer a Luc&iacute;a, sus miedos, sus inquietudes y tambi&eacute;n su deseo.
Os dejamos con la historia de Luc&iacute;a:</p>
<iframe src="http://player.vimeo.com/video/34603360" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
<p><a href="http://vimeo.com/34603360">Luc&iacute;a y el Mar</a> from <a href="http://vimeo.com/liquete">jorge liquete</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
<br/>
<p>La alegr&iacute;a de poder ayudar a muchas "Luc&iacute;as" y a sus familias, es lo que nos ha movido a creer en este proyecto.</p></br>
<p>Si tu tambi&eacute;n te quieres contagiar de esa alegr&iacute;a e ilusi&oacute;n, pues conceder un deseo a otra persona a trav&eacute;s de <b>DEZY</b>.</p>
</div>
<div class="one_half_last">
<p>
<h2>&iquest;C&oacute;mo ayudar?</h2>
Si est&aacute;s interesado en conceder un deseo, un miembro de nuestra asociaci&oacute;n trabajar&aacute; directamente contigo en la selecci&oacute;n de un deseo y en llevarlo a cabo.
</p>
</br>
<p>
Hay diversas maneras de ayudar a conceder un deseo: financiaci&oacute;n total, financiaci&oacute;n parcial o trueque. Tambi&eacute;n puedes colaborar compartiendo un deseo, ya que la visibilidad de los deseos es muy importante.
</p>
</br>
<p>
Si quieres m&aacute;s informaci&oacute;n, nos encontrar&aacute;s en el (+34) 619 135 352 y en <a href="mailto:hola@yosy.org">hola@yosy.org</a>
</p>
</br>
<p>
<b>&iexcl;No te pierdas la experiencia de ayudar a cumplir un sue&ntilde;o!</b></p>
<img src="${resource(dir:'images',file:'conceder_deseo.png')}" alt="YOSY" class="img_conceder"/>
</div>
</div>

grails-app/views/index/_makeWhis.gsp
<%@ page import="org.yosy.Deseo"%>
<%@ page import="org.yosy.Localidad"%>
<%@ page import="org.yosy.Categoria"%>
<link rel="stylesheet" href="${resource(dir:'js',file:'chosen/chosen.css')}" />
<g:javascript library="jquery" plugin="jquery" />
<div class="pedir_deseo">
	<g:formRemote url="[ controller: 'index', action: 'save']" name="login" on401="showLogin(); return false;" onSuccess="return false;">
		<div class="caja_deseo">
			<div class="titulo_deseo">Pide un deseo</div>
			<div class="cuerpo_deseo">
				<div id="firstStep">
					<g:textArea name="descripcion"
						value="${deseoInstance?.descripcion}" />
					<div class="tip_deseo">
						Ejemplo: ir al circo, ver los cisnes, comer paella...
					</div>
				</div>
				<div id="secondStep">
					<div>
						<div class="titulo_label_form_deseo">
							<span>
								Título
							</span>
							<g:textField name="titulo" value="${deseoInstance?.titulo}" class="titulo_form_deseo"/>
						</div>
						<div class="loc_form_deseo">
							<span class="loc_label_form_deseo">
								Localidad
							</span>
							<select data-placeholder="Elige la localidad..." class="chzn-select" name="localidad" id="localidad" style="width:275px; margin-right: 15px; margin-top: 10px;">
								<option value="" ></option>
								<g:each in="${localidad}" status="i" var="loc">
									<option value="${loc.nombre}" >${loc.nombre}</option> 
								</g:each>
							</select>
						</div>
						<div class="cat_form_deseo">
							<span class="cat_label_form_deseo">
								Categoría
							</span>
							<select data-placeholder="Elige la categoría..." class="chzn-select" name="categoria" id="categoria" style="width:275px; margin-right: 15px; margin-top: 10px;">
								<option value="" ></option>
								<g:each in="${categoria}" status="i" var="cat">
									<option value="${cat.nombre}" >${cat.nombre}</option> 
								</g:each>
							</select>
						</div>
					</div>
					<div class="tip_deseo" >	
						Ayudanos a entender y localizar tu deseo :) 
						<div style="display:none;">	
							<g:submitToRemote id="botonEnviarRemote" style="visibility:hidden" url="[controller: 'index', action: 'save']" onFailure="showLogin()" onSuccess="showResponseRedirect('Deseo creado',hostName+'index/list'); " name="create" class="rightButton" value="${message(code: 'default.button.send.label', default: 'Enviar')}" />
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="firstStepButton" onclick="$('#firstStep').hide(); $('#firstStepButton').hide(); $('#secondStep').show(); $('#secondStepButton').show(); return false;" class="enviar_deseo">
			<img src="${resource(dir:'images',file:'boton.png')}" style="width: 400px; height: 47px; cursor: pointer;" />
			<div class="continuar_deseo">
				Continuar
			</div>
		</div>
		<div id="secondStepButton" style="display: none" class="enviar_deseo">
			<img src="${resource(dir:'images',file:'boton.png')}" style="width: 190px; height: 47px; margin: 0 3% 0 0; cursor: pointer;" />
			<img src="${resource(dir:'images',file:'boton.png')}" style="width: 190px; height: 47px; cursor: pointer;" />
			<div class="continuar_paso_dos_deseo">
				<span onclick="$('#firstStep').show(); $('#firstStepButton').show(); $('#secondStep').hide(); $('#secondStepButton').hide(); return false;" class="atras_deseo">
					Volver
				</span>
				<span onclick="setCode('$(\'#botonEnviarRemote\').click();'); $('#botonEnviarRemote').click()" class="enviar_fin_deseo">
					Enviar
				</span>
			</div>
		</div>
	</g:formRemote>
</div>
<div class="instructions">
	<div class="title_instructions">
		¿Cómo funciona?
	</div>
	<div class="content_instructions">
		<ul class="pasos_instructions">
			<li class="paso_instructions paso_uno">
				<img alt="paso uno" src="${resource(dir:'images',file:'marco.png')}" class="image_instructions">
				<div class="pie_instructions">
					<div class="titulo_pie_instructions">Pide un deseo</div>
					Lucía quiere ir al mar y lo ha escrito en Dezy</br>
				</div>
			</li>
			<li class="paso_instructions paso_dos">
				<img alt="paso uno" src="${resource(dir:'images',file:'marco.png')}" class="image_instructions">
				<div class="pie_instructions">
					<div class="titulo_pie_instructions">
						Compártelo hasta que alguien lo lea
					</div>
					Hugo, Andrea y Pablo han visto el deseo de Lucía
				</div>
			</li>
			<li class="paso_instructions paso_tres">
				<img alt="paso uno" src="${resource(dir:'images',file:'marco.png')}" class="image_instructions">
				<div class="pie_instructions">
					<div class="titulo_pie_instructions">
						Hazlo realidad
					</div>
					Gracias a Dezy, Lucía puede conocer el mar</br>
				</div>
			</li>
		</ul>
	</div>
</div>
<script src="${resource(dir:'js',file:'chosen/chosen.jquery.js')}"
	type="text/javascript"></script>
<script type="text/javascript"> 
  	$(".chzn-select").chosen({no_results_text: "No se han encontrado resultados para:"});
</script>

grails-app/views/index/_privacy_policy.gsp
<g:javascript library="jquery" plugin="jquery" />
<div class="texto_privacy">
<div class="navigacion_nivel_dos">
	<g:link controller="index" class="navigacion_nivel_uno">
							Inicio
						</g:link>
		&nbsp; > Pol&iacute;tica de privacidad
</div>
<p>
	En cumplimiento de la LOPD, Ley 15/1999, de 13 de diciembre, de protecci&oacute;n de datos de car&aacute;cter personal, 
	se informa que los datos de car&aacute;cter personal que usted facilita, incluido su direcci&oacute;n de  correo electr&oacute;nico, 
	y que resultan necesarios para la formalizaci&oacute;n, gesti&oacute;n administrativa, ejecuci&oacute;n y desarrollo de la actividad propia de la 
	Asociaci&oacute;n sin &aacute;nimo de lucro YOSY (en lo sucesivo YOSY) se incluir&aacute;n en nuestros ficheros de datos personales, 
	cuyo &uacute;nico responsable y titular es YOSY.
</p>

<p>
	Asimismo, al remitir el interesado de forma voluntaria sus datos de car&aacute;cter personal a YOSY, autoriza expresamente 
	la utilizaci&oacute;n de los mismos a efectos de comunicaci&oacute;nes peri&oacute;dicas, incluyendo expresamente las que se realicen v&iacute;a 
	correo electr&oacute;nico o SMS que YOSY puede llevar a cabo con sus socios y posibles interesados inform&aacute;ndo de sus actividades, 
	noticias, proyectos, programas, as&iacute; como cuaquier otra oferta de productos y servicios relacionados con la actividad que se desarrolla. 
	Estos datos en ning&uacute;n caso son facilitados a otras empresas o personas ajenas a la organizaci&oacute;n.
</p>

<p>
	Puede ejercer sus derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n y oposici&oacute;n, dirigi&eacute;ndose por escrito mediante carta o 
	correo electr&oacute;nico a <a href="mailto:hola@yosy.org">hola@yosy.org</a>
</p>
<p>
	Para cumplir con lo establecido en la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la informaci&oacute;n y 
	comercio electr&oacute;nico (LSSI-CE), a continuaci&oacute;n se indican los datos del titular de este sitio web: <br/>
	<b>ASOCIACI&Oacute;N YOSY</b> <br/>
	Calle Doctor Casas 20 Planta 1 <br/>
	50008 de Zaragoza (Espa&ntilde;a)<br/>
	CIF: G99333676 <br/>
	Asociaci&oacute;n inscrita en el Registro General de Asociaciones de la Comunidad Aut&oacute;noma de Arag&oacute;n, con el n&uacute;mero 01-Z-3290-2011.
</p>
<p>
	&copy; YOSY 2011 - Asociaci&oacute;n YOSY | Todos los derechos reservados
</p>

grails-app/views/index/_whisDetails.gsp
<div class="lista_deseos">
	<div class="navigacion_nivel_dos">
		<g:link controller="index" class="navigacion_nivel_uno">Inicio</g:link>
		&nbsp; > Ver Deseos >
		${fieldValue(bean: deseoInstance, field: "titulo")}
	</div>
	<div class="deseo_detalle">
		<div class="lista_deseo_imagen_marco">
			<g:if test="${deseoInstance.usuario.image == 1}">
				<img src="${resource(dir:'images',file:'cara_uno.png')}"
					alt="cara :D" onmousedown="return false;"
					class="lista_deseo_imagen" />
			</g:if>
			<g:elseif test="${deseoInstance.usuario.image == 2}">
				<img src="${resource(dir:'images',file:'cara_dos.png')}"
					alt="cara :D" onmousedown="return false;"
					class="lista_deseo_imagen" />
			</g:elseif>
			<g:else>
				<img src="${resource(dir:'images',file:'cara_tres.png')}"
					alt="cara :D" onmousedown="return false;"
					class="lista_deseo_imagen" />
			</g:else>
		</div>
		<div class="lista_deseo_nombre">
			${deseoInstance.usuario.nombre}
		</div>
		<div class="lista_deseo_titulo">
			<g:link action="whisDetail" controller="index"
				params="[idWhis: deseoInstance.id]" style="text-decoration: none;">
				${fieldValue(bean: deseoInstance, field: "titulo")}
			</g:link>
		</div>
		<div class="lista_deseo_descripcion">
			${fieldValue(bean: deseoInstance, field: "descripcion")}
		</div>

		<div class="lista_deseo_social">
			<div class="lista_deseo_cat">
				${deseoInstance.categoria?.nombre}
			</div>
			<div class="lista_deseo_loc">
				${deseoInstance.localidad?.nombre}
			</div>
			<!--  <div class="lista_deseo_comment">-->
			<div class="example-commentheading">
				<a style="padding: 0px 10px 0px 10px;" title="Ver comentarios."
					class="linkBlack"
					onclick="$('#divFormWish${deseoInstance.id}').toggle('slow'); return false;">
					${deseoInstance.comentarios.size()} comentarios
				</a>
			</div>
			<div id="divFormWish${deseoInstance.id}" class="arrow_box"
				style="display: none">
				<span class="equis_cerrar"
					onclick="$('#divFormWish${deseoInstance.id}').toggle('slow'); return false;">X</span>
				</br>
				<g:each in="${deseoInstance.comentarios}" status="u"
					var="comentarioInstance">
					<img src="${resource(dir:'images',file:'cara_uno.png')}"
						alt="cara :D" onmousedown="return false;"
						class="imagen_comentario" />
					<div class="texto_comentario">
						<span class="nombre_comentario"> ${comentarioInstance.autor}
						</span></br>
						${comentarioInstance.texto}</br>
						${comentarioInstance.fecha.format("dd/MM/yyyy - hh:mm")}</br>
					</div>
				</g:each>
				<div>
					<g:formRemote name="commentForm"
						url="[ controller: 'index', action: 'createComment']">
						<g:hiddenField name="id" value="${deseoInstance.id}" />
						<g:textArea name="texto" class="anadir_texto_comentario"></g:textArea>
						<g:submitToRemote name="botonAnadirComentario${deseoInstance.id}"
							class="anadir_comentario" controller="index"
							action="createComment" value="Añadir comentario"
							onFailure="showLogin(); return false;"
							onSuccess="showResponse('Comentario creado'); jQuery('[name=comentarios${deseoInstance.id}]').text('Gracias!'); clear('commentList${deseoInstance.id}'); return false;"
							update="commentList${deseoInstance.id}" />
						<img
							onclick="$('[name=botonAnadirComentario${deseoInstance.id}]').click()"
							src="${resource(dir:'images',file:'boton.png')}"
							style="cursor: pointer; height: 54px; width: 570px; margin: 0 0 0 3%;" />
						<div class="anadir_comentario_texto"
							onclick="setCode('$(\'[name=botonAnadirComentario${deseoInstance.id}]\').click()'); $('[name=botonAnadirComentario${deseoInstance.id}]').click()">
							Añadir Comentario</div>
					</g:formRemote>
				</div>
			</div>
			<div class="lista_deseo_twitter">
				<a href="https://twitter.com/share" class="twitter-share-button"
					data-text='"${fieldValue(bean: deseoInstance, field: "titulo")}"'
					data-via="dezy" data-size="large"> Tweet </a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="lista_deseo_fb">
				<div id="fb-root"></div>
				<script>
					(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
				  		js = d.createElement(s); js.id = id;
				  		js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=393740090668791";
				  		fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
				</script>
				<div class="fb-like"
					data-href="/index/whisDetail?idWhis=${deseoInstance.id}"
					data-send="false" data-layout="box_count" data-width="70"
					data-show-faces="false" data-font="tahoma"></div>
			</div>
			<div class="lista_deseo_votos">
				<g:remoteLink class="imagen_votos" controller="index" action="vote"
					id="${deseoInstance.id}" onFailure="showLogin(); return false;"
					name='votar${deseoInstance.id}'
					onSuccess="showResponse(data); jQuery('[name=votos${deseoInstance.id}]').text('Gracias!'); return false;">
					<img
						onclick="setCode('$(\'[name=votar${deseoInstance.id}]\').click()'); $('[name=votar${deseoInstance.id}]').click()"
						src="${resource(dir:'images',file:'thumbs_up_azul_dcha.png')}"
						style="max-height: 30px; cursor: pointer; border: none;" />
				</g:remoteLink>
				<g:remoteLink class="texto_votos" controller="user"
					action="listUserVotes" id="${deseoInstance.id}"
					name="votos${deseoInstance.id}"
					onFailure="showResponse('Ha ocurrido un error'); return false;"
					onSuccess="showResponseHtml(data); return false;">
					${deseoInstance.votos.size()} votos
						</g:remoteLink>
			</div>
			<img class="lista_deseo_estrellas"
				src="${resource(dir:'images',file:'estrellitas.png')}">
		</div>
	</div>
</div>

grails-app/views/index/_whisesList.gsp
<g:javascript library="jquery" plugin="jquery" />
<div class="lista_deseos">
	<div class="navigacion_nivel_dos">
		<g:link controller="index" class="navigacion_nivel_uno">Inicio</g:link>
		&nbsp; > Ver deseos
	</div>
	<ul>
		<g:each in="${deseoInstanceList}" status="i" var="deseoInstance">
			<li class="lista_deseo">
				<div class="lista_deseo_imagen_marco">
					<g:if test="${deseoInstance.usuario.image == 1}">
						<img src="${resource(dir:'images',file:'cara_uno.png')}"
							alt="cara :D" onmousedown="return false;"
							class="lista_deseo_imagen" />
					</g:if>
					<g:elseif test="${deseoInstance.usuario.image == 2}">
						<img src="${resource(dir:'images',file:'cara_dos.png')}"
							alt="cara :D" onmousedown="return false;"
							class="lista_deseo_imagen" />
					</g:elseif>
					<g:else>
						<img src="${resource(dir:'images',file:'cara_tres.png')}"
							alt="cara :D" onmousedown="return false;"
							class="lista_deseo_imagen" />
					</g:else>
				</div>
				<div class="lista_deseo_nombre">
					${deseoInstance.usuario.nombre}
				</div>
				<div class="lista_deseo_titulo">
					<g:link action="whisDetail" controller="index"
						params="[idWhis: deseoInstance.id]" style="text-decoration: none;">
						${fieldValue(bean: deseoInstance, field: "titulo")}
					</g:link>
				</div>
				<div class="lista_deseo_descripcion">
					${fieldValue(bean: deseoInstance, field: "descripcion")}
				</div>

				<div class="lista_deseo_social">
					<div class="lista_deseo_cat">
						${deseoInstance.categoria?.nombre}
					</div>
					<div class="lista_deseo_loc">
						${deseoInstance.localidad?.nombre}
					</div>
					<!--  <div class="lista_deseo_comment">-->
					<div class="example-commentheading">
						<a style="padding: 0px 10px 0px 10px;" title="Ver comentarios."
							name="comentarios${deseoInstance.id}" class="linkBlack"
							onclick="$('#divFormWish${deseoInstance.id}').toggle('slow'); return false;">
							${deseoInstance.comentarios.size()} comentarios
						</a>
					</div>
					<div id="divFormWish${deseoInstance.id}" class="arrow_box"
						style="display: none">
						<span class="equis_cerrar"
							onclick="$('#divFormWish${deseoInstance.id}').toggle('slow'); return false;">X</span>
						</br>
						<g:each in="${deseoInstance.comentarios}" status="u"
							var="comentarioInstance">
							<img src="${resource(dir:'images',file:'cara_uno.png')}"
								alt="cara :D" onmousedown="return false;"
								class="imagen_comentario" />
							<div id="commentWishId${comentarioInstance.id}" class="texto_comentario">
								<span class="nombre_comentario"> ${comentarioInstance.autor}
								</span></br>
								${comentarioInstance.texto}</br>
								${comentarioInstance.fecha.format("dd/MM/yyyy - hh:mm:ss")}</br>
							</div>
							<g:if test="${u == deseoInstance.comentarios.size() - 1}">
								<div id="lastDateComment${deseoInstance.id}" style="display: none">
										${comentarioInstance.fecha.format("dd/MM/yyyy - HH:mm:ss")}
								</div>
							</g:if>
						</g:each>
						<div id="newComments${deseoInstance.id}">
						</div>
						<div>
							<span id="updCommentsSpan${deseoInstance.id}" onclick="updateComments(${deseoInstance.id},$('#lastDateComment${deseoInstance.id}'));">Actualizar</span>
						</div>
						<div>
							<g:formRemote name="commentForm"
								url="[ controller: 'index', action: 'createComment']">
								<g:hiddenField name="id" value="${deseoInstance.id}" />
								<g:textArea name="texto" class="anadir_texto_comentario"></g:textArea>
								<g:submitToRemote
									name="botonAnadirComentario${deseoInstance.id}"
									class="anadir_comentario" controller="index"
									action="createComment" value="Añadir comentario"
									onFailure="showLogin(); return false;"
									onSuccess="showResponse('Comentario creado'); jQuery('[name=comentarios${deseoInstance.id}]').text('Gracias!'); clear('commentList${deseoInstance.id}'); jQuery('#updCommentsSpan${deseoInstance.id}').click(); return false;"
									update="commentList${deseoInstance.id}" />
								<img
									onclick="$('[name=botonAnadirComentario${deseoInstance.id}]').click()"
									src="${resource(dir:'images',file:'boton.png')}"
									style="cursor: pointer; height: 54px; width: 570px; margin: 0 0 0 3%;" />
								<div class="anadir_comentario_texto"
									onclick="setCode('$(\'[name=botonAnadirComentario${deseoInstance.id}]\').click()'); $('[name=botonAnadirComentario${deseoInstance.id}]').click()">
									Añadir Comentario</div>
							</g:formRemote>
						</div>
					</div>
					<div class="lista_deseo_twitter">
						<div id="custom-tweet-button">
							<script>
								//Obtenemos los numero de facebook y twitter.
								CountTwitter("/index/whisDetail?idWhis=${deseoInstance.id}");
								CountFacebook("/index/whisDetail?idWhis=${deseoInstance.id}");
							</script>
							<a
								href="https://twitter.com/share?url=http%3A%2F%2Fwww.dezy.es%2Findex%2FwhisDetail?idWhis=${deseoInstance.id}&text=Haz%20realidad%20${fieldValue(bean: deseoInstance, field: "titulo")}&via=dezy&size=large"
								target="_blank"> <label
								id="lblCountTwitter${deseoInstance.id}"></label>
							</a>

						</div>
					</div>
					<label id="lblCountFacebook${deseoInstance.id}"></label>
					<div class="lista_deseo_fb">
						<div id="fb-root"></div>
						<script>(function(d, s, id) {
						  var js, fjs = d.getElementsByTagName(s)[0];
						  if (d.getElementById(id)) return;
						  js = d.createElement(s); js.id = id;
						  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=393740090668791";
						  fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>
						<div class="fb-like"
							data-href="http://www.dezy.es/index/whisDetail?idWhis=${deseoInstance.id}"
							data-send="false" data-layout="box_count" data-width="75"
							data-show-faces="false" data-font="tahoma"></div>
					</div>
					<div class="lista_deseo_votos">
						<g:remoteLink class="imagen_votos" controller="index"
							action="vote" id="${deseoInstance.id}"
							onFailure="showLogin(); return false;"
							name='votar${deseoInstance.id}'
							onSuccess="showResponse(data); jQuery('[name=votos${deseoInstance.id}]').text('Gracias!'); return false;">
							<img
								onclick="setCode('$(\'[name=votar${deseoInstance.id}]\').click()'); $('[name=votar${deseoInstance.id}]').click()"
								src="${resource(dir:'images',file:'thumbs_up_azul_dcha.png')}"
								style="max-height: 30px; cursor: pointer; border: none;" />
						</g:remoteLink>
						<g:remoteLink class="texto_votos" controller="user"
							action="listUserVotes" id="${deseoInstance.id}"
							name="votos${deseoInstance.id}"
							onFailure="showResponse('Ha ocurrido un error'); return false;"
							onSuccess="showResponseHtml(data); return false;">
							${deseoInstance.votos.size()} votos
						</g:remoteLink>
					</div>
					<img class="lista_deseo_estrellas"
						src="${resource(dir:'images',file:'estrellitas.png')}">
				</div>
			</li>
		</g:each>
	</ul>
	<div class="indexPaging">
		<g:paginate controller="index" action="list"
			total="${deseoInstanceTotal}" />
	</div>
</div>